### ISSUE TITLE
Compute standard PH barcode.

### ISSUE THREAD

**Issue by kjemmett** [RabadanLab/TARGet#4]
Let's say I just want to compute the standard PH barcode of a dataset using TARGet. I don't think this can be done at present. Here's two possible ways:

1) Introduce a new flag to set the _minimum_ number of segregating sites to consider. When equal to the total number of segregating sites this should recover standard PH. I think this might be an interesting flag for other purposes as well...
2) Introduce a flag to specifically compute standard PH.

**Comment by pcamara** [comment]
I think you are right, truncating s from below might give some extra info,
for instance whether two small loops share an edge (so that there is also a
large loop containing them which is not independent). So it might be in
fact interesting to implement that feature in TARGet (in the first way that
you propose). Ideally, one would like to be also able to further tune s
interactively in the GUI (within the limits already specified in the
command line, and hence pre-computed). A nice implementation for that could
be sliders <http://matplotlib.org/examples/widgets/slider_demo.html> .
However, the problem with that interactive feature is that optimize_barcode
can very slow.

**Comment by pcamara** [comment]
This feature is now implemented in TARGet, flag -t.
